AWSTemplateFormatVersion: 2010-09-09
Description: Create a VPC and an assumable role for cross account VPC peering.
Parameters:
  AWSTemplateFormatVersion: 2010-09-09
Description: Create a VPC and an assumable role for cross account VPC peering.

# Parameters
Parameters:
  RequesterVPCAccountCidr:
    Description: The VPC cidr of the requester account
    Type: String
    Default: 172.16.0.0/16

  RequesterVPCAccountID:
    Description: Africanfinancial aws account id 
    Type: String
    Default: 258972849027 

  PeerVPCAccountCidr:
    Description: The VPC cidr of the peer account
    Type: String
    Default: 192.168.0.0/16
  
  PeerVPCAccountID:
    Description: Another aws account id for a peering connection
    Type: String
    Default: 899624289050

  PeerVPCId:
    Description: The vpc id of the peer account
    Type: String
    Default: vpc-05827b72cfd6f8327
  

  PeerRoleArn:
    Description: The arn of the peer role created in the accepter account
    Type: String   

Resources:
 
   # VPC Peering
  vpcPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties: 
      VpcId: !ImportValue TigerProject3ArchitectureStack-VPCID
      PeerOwnerId: !Ref PeerVPCAccountID
      PeerRegion: us-east-1
      PeerRoleArn:  !Ref PeerRoleArn
      PeerVpcId: !Ref PeerVPCId
      Tags: 
        - Key : name
          Value: AfricanFinancialVpcPeeringConnetion
      


   