---
AWSTemplateFormatVersion: '2010-09-09'
Metadata:
 License: Apache-2.0
Description: 'AWS CloudFormation Sample Template IAM_Users_Groups_and_Policies: Sample
  template showing how to create IAM users, groups and policies. It creates a single'

Parameters:
  # Cloudspace engineers password
  CloudspaceEngPassword:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '20'
    ConstraintDescription: the password must be between 1 and 20 characters

  # African Financial Users  password
  AfricanFinancialPassword:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '20'
    ConstraintDescription: the password must be between 1 and 20 characters 

# Ressources
Resources:
# Cloudspace Enigeer users
  TigerUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: Charlotte1
      LoginProfile:
        Password: !Ref 'CloudspaceEngPassword'
  TigerUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: Hortense1
      LoginProfile:
        Password: !Ref 'CloudspaceEngPassword'
  TigerUser3:
    Type: AWS::IAM::User
    Properties:
      UserName: Lynda1
      LoginProfile:
        Password: !Ref 'CloudspaceEngPassword'
  TigerUser4:
    Type: AWS::IAM::User
    Properties: 
      UserName: Cedric1
      LoginProfile:
        Password: !Ref 'CloudspaceEngPassword'
  TigerUser5:
    Type: AWS::IAM::User
    Properties:
      UserName: Alain1
      LoginProfile:
        Password: !Ref 'CloudspaceEngPassword'

  # Cloudspace Enigeers group
  CloudSpaceEngineersTigerGroup:
    Type: AWS::IAM::Group
    Properties:
     GroupName: CloudSpaceEngineersGroup

  # Cloudspace Engineer user to group association
  TigerUsers: 
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'CloudSpaceEngineersTigerGroup'
      Users:
       - !Ref TigerUser1
       - !Ref TigerUser2
       - !Ref TigerUser3
       - !Ref TigerUser4
       - !Ref TigerUser5

  # Cloudspace Engineer user restrictions (policies)
  CloudSpaceEngineersUserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudSpaceEngineersUserPolicy
      PolicyDocument:
        Statement:
        - Effect: Deny
          Action: ['aws-portal:*']
          Resource: '*'
      Groups: [!Ref 'CloudSpaceEngineersTigerGroup'] 

  # African Financial Security team users
  AfricanFinancialSecurityUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: IdrissSecurity
      LoginProfile:
        Password: !Ref 'AfricanFinancialPassword'
  AfricanFinancialSecurityUser2:      
    Type: AWS::IAM::User
    Properties:
      UserName: NarcisseSecurity
      LoginProfile:
        Password: !Ref 'AfricanFinancialPassword'
  AfricanFinancialSecurityUser3:        
    Type: AWS::IAM::User
    Properties:
      UserName: ClaudioSecurity
      LoginProfile:
        Password: !Ref 'AfricanFinancialPassword' 

  # African Financial Security team group
  AfricanFinancialSecurityGroup:
    Type: AWS::IAM::Group
    Properties:
     GroupName: AfricanFinancialSecurityGroupN

  # African Financial Security team users to group association
  AfricanFinancialSecurityUsers: 
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'AfricanFinancialSecurityGroup'
      Users:
       - !Ref AfricanFinancialSecurityUser1
       - !Ref AfricanFinancialSecurityUser2
       - !Ref AfricanFinancialSecurityUser3

  # African Financial Security team restrictions (policies)
  AfricanFinancialSecurityUserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AfricanFinancialSecurityUserPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['*']
          Resource: '*'  
      Groups: [!Ref 'AfricanFinancialSecurityGroup']  

  # African Financial Operation team users
  AfricanFinancialOperationUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: IdrissOperation
      LoginProfile:
        Password: !Ref 'AfricanFinancialPassword'
  AfricanFinancialOperationUser2:      
    Type: AWS::IAM::User
    Properties:
      UserName: NarcisseOperation
      LoginProfile:
        Password: !Ref 'AfricanFinancialPassword'
  AfricanFinancialOperationUser3:        
    Type: AWS::IAM::User
    Properties:
      UserName: ClaudioOperation
      LoginProfile:
        Password: !Ref 'AfricanFinancialPassword' 

  # African Financial Operation team group
  AfricanFinancialOperationGroup:
    Type: AWS::IAM::Group
    Properties:
     GroupName: AfricanFinancialOperationGroupN

  # African Financial Operation team users to group association
  AfricanFinancialOperationUsers: 
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'AfricanFinancialOperationGroup'
      Users:
       - !Ref AfricanFinancialOperationUser1
       - !Ref AfricanFinancialOperationUser2
       - !Ref AfricanFinancialOperationUser3

  # African Financial Operation team users restrictions (policies)
  AfricanFinancialOperationUserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AfricanFinancialOperationUserPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['*']
          Resource: '*'
          Condition:
            StringEquals:
            # StringNotEquals:
              aws:RequestedRegion: us-east-1
      Groups: [!Ref 'AfricanFinancialOperationGroup']                                        

  # # N2G Auditing team users
  # N2GAudingUser1:
  #   Type: AWS::IAM::User
  #   Properties:
  #     UserName: IdrissN2G
  #     LoginProfile:
  #       Password: !Ref 'AfricanFinancialPassword'
  # N2GAudingUser2:      
  #   Type: AWS::IAM::User
  #   Properties:
  #     UserName: NarcisseN2G
  #     LoginProfile:
  #       Password: !Ref 'AfricanFinancialPassword'
  # N2GAudingUser3:        
  #   Type: AWS::IAM::User
  #   Properties:
  #     UserName: ClaudioN2G
  #     LoginProfile:
  #       Password: !Ref 'AfricanFinancialPassword' 

  # # N2G Auditing team group
  # N2GAudingGroup:
  #   Type: AWS::IAM::Group
  #   Properties:
  #    GroupName: N2GAudingGroupN
     
  # # N2G Auditing team users to group association
  # N2GAudingUsers: 
  #   Type: AWS::IAM::UserToGroupAddition
  #   Properties:
  #     GroupName: !Ref 'N2GAudingGroup'
  #     Users:
  #      - !Ref N2GAudingUser1
  #      - !Ref N2GAudingUser2
  #      - !Ref N2GAudingUser3
